[programs.devnet]
myepicproject = "6TUpy4UtLx2eRi3Wdf8X558Zc21EhEw5Ea1LHBLHoGFj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kevinkuang/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
